Feature branch
bellom/Restaurant-Page pull request #2
Opened 2019-08-08 16:24 UTC by bellom

Kindly review

2019-08-08 18:50 UTC, nidalaa requested changes
Hi @bellom ! Nice job here :)

This is not a full review - as we agreed I am here testing some of the GH features :)

I lef one comment though :)

2019-08-08 18:50 UTC, nidalaa commented on package.json
> +{
Make sure you also use `package.lock` file. Thanks to this you will avoid problems with future versions of the dependencies 💪

2019-08-12 05:42 UTC, dipto0321 approved these changes
Hi @bellom ,

Good job 👏 . This is a basic app for testing your learning on webapck. So I didn't find any major issues. Except for this one 
![2019-08-12_113552](https://user-images.githubusercontent.com/6507903/62847048-e9fa1180-bcf5-11e9-8abf-b1948a9c7e31.jpg)
After fixing this design you can merge it. This is from me 👍 

[**Note:** Here is a good [tutorial ](https://www.youtube.com/watch?v=MpGLUVbqoYQ) about webpack. You can go for it to gain more about webpack]

Thanks 🙏

2019-08-13 12:51 UTC, bellom commented
Design didn't break on my system.

2019-08-13 13:32 UTC, dipto0321 commented
HI @bellom ,

Then Go ahead. 🙂 

Thanks 🙏

2019-08-13 16:37 UTC, merged